spring:
  application:
    name: demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url:
    dbcp2:
      min-idle: 50
      max-idle: 1000
      max-wait-millis: 1000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

